audio/urls.py
from django.urls import path
from . import views


app_name = 'audio'
urlpatterns = [
    path('', views.index, name='index'),
    path('input/', views.input, name='input'),
    path('submit/', views.submit, name='submit'),
]

user/urls.py
from django.urls import path
from . import views


app_name = 'user'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('zoom/auth/init/', views.zoom_init, name='zoom_init'),
    path('zoom/auth/return/', views.zoom_return, name='zoom_return'),
]

zoom_auto_records/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('audio/', include('audio.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

audio/models.py
from django.db import models


class AudioFile(models.Model):
    file = models.FileField(upload_to='audio/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils import timezone

# Create your models here.


class CustomUser(AbstractUser):
    zoom_code = models.CharField(max_length=255, blank=True)
    zoom_access_token = models.CharField(max_length=255, blank=True)
    zoom_refresh_token = models.CharField(max_length=255, blank=True)
    zoom_expires_in = models.DateTimeField(null=True)
    pass

    def has_valid_token(self):
        empty = self.zoom_access_token == ''
        expired = (not self.zoom_expires_in) or (
            self.zoom_expires_in <= timezone.now())
        return not (empty or expired)


class CustomUserManager(BaseUserManager):
    pass

audio/forms.py
from django import forms

from audio.models import AudioFile
from audio.validators import FileSizeValidator


class AudioFileForm(forms.ModelForm):
    file = forms.FileField(
        validators=[FileSizeValidator(val=200, byte_type="mb")],
        required=True,
    )
    meeting_uuid = forms.CharField(required=True)

    class Meta:
        model = AudioFile
        fields = ('file',)

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class SignUpForm(UserCreationForm):
    class Meta:
        User = get_user_model()
        model = User
        fields = ['username', 'email', 'password1', 'password2']

audio/views.py
import os

from django.http import HttpResponse
from django.shortcuts import render
from audio.forms import AudioFileForm
from audio.models import AudioFile
from audio.domain_logic import access_zoom_api_with_access_token, access_zoom_api_with_jwt, recognize_speech, convert_m4a_to_flac


def index(request):
    return render(request, 'audio/index.html')


def input(request):
    meeting_id = request.POST['meeting_id'].replace(' ', '')
    user = request.user

    list_past_meeting_instances = {
        'method': 'GET',
        'uri': '/v2/past_meetings/' + meeting_id + '/instances',
    }
    past_meetings = access_zoom_api(user, list_past_meeting_instances)

    return render(request, 'audio/input.html', {'past_meetings': past_meetings['meetings']})


def submit(request):
    form = AudioFileForm(request.POST, request.FILES)  # not tested
    if not form.is_valid():
        return HttpResponse("fail %s" % form.errors)

    file_instance = AudioFile(file=request.FILES['file'])
    file_instance.save()
    meeting_uuid = request.POST['meeting_uuid']
    user = request.user

    get_past_meeting_details = {
        'method': 'GET',
        'uri': '/v2/past_meetings/' + meeting_uuid,
    }
    meeting = access_zoom_api(user, get_past_meeting_details)

    record = get_record_from_file(file_instance)
    delete_file_and_instance(file_instance)

    context = {
        'uuid': meeting['uuid'],
        'topic': meeting['topic'],
        'start_time': meeting['start_time'],
        'end_time': meeting['end_time'],
        'total_minutes': meeting['total_minutes'],
        'participants_count': meeting['participants_count'],
        'record': record,
    }  # not tested

    return render(request, 'audio/submit.html', context)  # not tested


def access_zoom_api(user, api):
    if user.is_anonymous:
        past_meetings = access_zoom_api_with_jwt(api)
        return past_meetings

    if user.has_valid_token():
        access_token = user.zoom_access_token
        past_meetings = access_zoom_api_with_access_token(
            api, access_token)
    else:
        past_meetings = access_zoom_api_with_jwt(api)

    return past_meetings


def get_record_from_file(file_instance):
    file_path = file_instance.file.path
    converted_file_path = 'audio/tmp/converted.flac'

    convert_m4a_to_flac(file_path, converted_file_path)
    record = recognize_speech(converted_file_path, 'ja-JP')

    delete_file(converted_file_path)

    return record


def delete_file(file_path):
    if os.path.isfile(file_path):
        os.remove(file_path)


def delete_file_and_instance(file_instance):
    path = file_instance.file.path
    delete_file(path)
    file_instance.delete()

user/views.py
import base64
import datetime
import json
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from audio.domain_logic import get_secret
import http

from user.forms import SignUpForm


def index(request):
    return render(request, 'user/index.html')


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = 'user/signup.html'
    success_url = reverse_lazy('audio:index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())


@login_required
def zoom_init(request):
    uri = "https://zoom.us/oauth/authorize"
    response_type_query = "response_type=code"
    client_id_query = "client_id=" + get_secret('ZOOM_CLIENT_ID')
    redirect_uri_query = "redirect_uri=http://localhost:8000/user/zoom/auth/return"

    zoom_auth_url = uri + "?" + response_type_query + \
        "&" + client_id_query + "&" + redirect_uri_query
    return render(request, 'user/zoom_init.html', {'zoom_auth_url': zoom_auth_url})


@login_required
def zoom_return(request):
    if 'code' in request.GET:
        code = request.GET.get('code')
    else:
        code = "couldn't get code"
        return HttpResponse(code)

    user = request.user
    user.zoom_code = code
    user.save()

    data = get_zoom_access_token(code)
    user.zoom_access_token = data['access_token']
    user.zoom_refresh_token = data['refresh_token']
    now = timezone.now()
    user.zoom_expires_in = now + datetime.timedelta(seconds=data['expires_in'])
    user.save()
    return render(request, 'user/zoom_return.html')


def get_zoom_access_token(code):
    client_id = get_secret('ZOOM_CLIENT_ID')
    client_secret = get_secret('ZOOM_CLIENT_SECRET')
    basic_auth = base64.b64encode(
        (client_id + ":" + client_secret).encode('utf-8'))
    headers = {'authorization': 'Basic' + basic_auth.decode('utf-8')}

    grant_type_query = 'grant_type=authorization_code'
    code_query = 'code=' + code
    redirect_uri_query = "redirect_uri=http://localhost:8000/user/zoom/auth/return"
    uri = '/oauth/token' + '?' + grant_type_query + \
        '&' + code_query + '&' + redirect_uri_query

    conn = http.client.HTTPSConnection('zoom.us')
    conn.request('POST', uri, headers=headers)
    response = conn.getresponse()
    data = response.read()
    return json.loads(data)

audio/templates/audio/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <title>Zoom Auto Records</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

audio/templates/audio/index.html
{% extends 'audio/base.html' %}
{% block content %}
<form action="{% url 'audio:input' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label>
        Zoom会議のミーティングID
        <input type="text" name="meeting_id">
    </label>
    <input type="submit" value="send">
</form>
{% endblock %}

audio/templates/audio/input.html
{% extends 'audio/base.html' %}
{% block content %}
<form action="{% url 'audio:submit' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    どのZoom会議？
    {% if past_meetings %}
    <ul>
        {% for meeting in past_meetings %}
        <li>
            <input type="radio" name="meeting_uuid" id="meeting{{ forloop.counter }}" value="{{ meeting.uuid }}" />
            <label for="meeting{{ forloop.counter }}">{{ meeting }}</label>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <label>
        Zoomの音声録音(m4a形式)
        <input type="file" name="file">
    </label>
    <input type="submit" value="send">
</form>
{% endblock %}

audio/templates/audio/submit.html
{% extends 'audio/base.html' %}
{% block content %}
<ul>
    <li>
        UUID: {{ uuid }}
    </li>
    <li>
        topic: {{ topic }}
    </li>
    <li>
        start_time: {{ start_time }}
    </li>
    <li>
        end_time: {{ end_time }}
    </li>
    <li>
        total_minutes: {{ total_minutes }}
    </li>
    <li>
        participants_count: {{ participants_count }}
    </li>
    <li>
        議事録：
    </li>
</ul>
<div>
    {{ record }}
</div>
{% endblock %}

user/templates/user/index.html
{% extends 'audio/base.html' %}
{% block content %}
<div>
    <form action="">
        {% csrf_token %}
        <label>
            メールアドレス
            <input type="email" name="email">
        </label>
        <label>
            パスワード
            <input type="password" name="password">
        </label>
        <input type="submit" value="ログイン">
    </form>
    <a href="{% url 'user:signup' %}">sign up page</a>
</div>
{% endblock %}

user/templates/user/login.html
{% extends 'audio/base.html' %}
{% block content %}
<div>
    <form action="">
        {% csrf_token %}
        <label>
            メールアドレス
            <input type="email" name="email">
        </label>
        <label>
            パスワード
            <input type="password" name="password">
        </label>
        <input type="submit" value="ログイン">
    </form>
    <a href="{% url 'user:signup' %}">sign up page</a>
</div>
{% endblock %}

user/templates/user/signup.html
{% extends 'audio/base.html' %}
{% block content %}
<div>
    <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            {{ field.label }}
            {{ field }}
            {{ field.errors }}
            <br>
        {% endfor %}
        <input type="submit" value="sign up">
    </form>
</div>
{% endblock %}

user/templates/user/zoom_init.html
{% extends 'audio/base.html' %}
{% block content %}
<div>
    Zoomとアプリ連携
    <a href="{{ zoom_auth_url }}">Zoomの連携ページへ</a>
</div>
{% endblock %}

user/templates/user/zoom_return.html
{% extends 'audio/base.html' %}
{% block content %}
<div>
    <p>
        Zoomと連携ができました。
    </p>
    <a href="{% url 'audio:index' %}">議事録作成ページへ</a>
</div>
{% endblock %}